In [1]:
import numpy as np
from numpy.linalg import inv, eigvals, solve

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [3]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
print(type(arr))
print(type(mat))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
l = [1,2,3,4,5]

np.array(l)

array([1, 2, 3, 4, 5])

In [6]:
np.array([l,l])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [7]:
arr[1]

20

In [8]:
arr[[0,1,3]]

array([10, 20, 40])

In [9]:
arr[1:4]

array([20, 30, 40])

In [10]:
mat[0,1]

2

In [11]:
r0 = mat[0,:]
r0

array([1, 2, 3, 4])

In [12]:
mat[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
mat[:, 1]

array([ 2,  6, 10, 14])

In [14]:
mat[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [15]:
m1 = np.array([[1, 1], [1, 1]])
m1

array([[1, 1],
       [1, 1]])

In [16]:
m2 = np.array([[2, 2], [2, 2]])
m2

array([[2, 2],
       [2, 2]])

In [17]:
m2 + m1

array([[3, 3],
       [3, 3]])

In [18]:
m2 - m1

array([[1, 1],
       [1, 1]])

In [19]:
10 * m1

array([[10, 10],
       [10, 10]])

In [20]:
m1/2  # 1/2をかけるのと同じ

array([[0.5, 0.5],
       [0.5, 0.5]])

In [21]:
m1*m2

array([[2, 2],
       [2, 2]])

In [22]:
m1@m2

array([[4, 4],
       [4, 4]])

In [23]:
np.dot(m1,m2)

array([[4, 4],
       [4, 4]])

In [24]:
m3 = np.array([[1,2,3],[4,5,6]])
m3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
m3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
m3.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([20,10])

In [28]:
sol = solve(a,b)

In [29]:
print(f'y = {sol[0]}\nx = {sol[1]}')

y = -30.0
x = 25.0


In [30]:
a = np.array([[1,2],[3,4]])
a_inv = inv(a)
b = np.array([20,10])
a_inv@b

array([-30.,  25.])

In [31]:
a = np.array([[1,2],[3,4]])
eigvals(a)

array([-0.37228132,  5.37228132])

In [32]:
dir(m3)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [33]:
m3.shape

(2, 3)

In [34]:
r0 = mat[0,:]
r0

array([1, 2, 3, 4])

In [35]:
r0_list = r0.tolist()

r0_list

[1, 2, 3, 4]

In [36]:
type(r0_list)

list

In [37]:
np.sqrt(4)

2.0

In [38]:
np.exp(10)

22026.465794806718

In [39]:
np.log(10)

2.302585092994046

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [44]:
xx = [1,2,3,4,5,6]
np.mean(xx)

3.5

In [45]:
np.median(xx)

3.5

In [46]:
np.var(xx,ddof=1)

3.5

In [47]:
np.std(xx,ddof=1)

1.8708286933869707

In [48]:
xy = [[1,2,3,4,5,6],[1,6,2,5,3,1]]
np.cov(xy,ddof=1)

array([[ 3.5, -0.6],
       [-0.6,  4.4]])

In [49]:
np.corrcoef(xy)

array([[ 1.        , -0.15289416],
       [-0.15289416,  1.        ]])

In [50]:
def utility(x,s):
    
    if s != 1:
        return (x**(1-s)-1) / (1-s)
    
    else:
        return np.log(x)

In [51]:
utility(10, 1)

2.302585092994046

In [52]:
utility(10, 0.2)

6.636966806002416

In [53]:
list0 = [1.0, 2.0, 3.0, 4.0, 5.0]

In [54]:
list1 = []

for i in list0:
    list1.append(i + 10)

list1

[11.0, 12.0, 13.0, 14.0, 15.0]

In [55]:
list0 + [10]

[1.0, 2.0, 3.0, 4.0, 5.0, 10]

In [56]:
list0 + 10

TypeError: can only concatenate list (not "int") to list

In [57]:
arr0 = np.array(list0)
arr0

array([1., 2., 3., 4., 5.])

In [58]:
arr0 + 10

array([11., 12., 13., 14., 15.])

In [59]:
arr0 - 5

array([-4., -3., -2., -1.,  0.])

In [60]:
arr0 * 10  

array([10., 20., 30., 40., 50.])

In [61]:
arr0 ** 2

array([ 1.,  4.,  9., 16., 25.])

In [62]:
np.sqrt(arr0)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [63]:
np.log(arr0)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [64]:
y = arr0 * 2 + np.sqrt(arr0) + 10
y

array([13.        , 15.41421356, 17.73205081, 20.        , 22.23606798])

In [65]:
mat0 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
mat0 * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [67]:
np.sqrt(mat0)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
np.log(mat0)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [69]:
i = 15   # I
g = 10   # G
d = 10   # d
c = 0.7  # c

a = np.array([[1,-c],[1,-1]])
b = np.array([i+g-d, 0])

In [70]:
sol = solve(a,b)
print(f'E = {sol[0]:.1f}\nY = {sol[1]:.1f}')

E = 50.0
Y = 50.0


In [71]:
r_list = range(0, 10)
list(r_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
f = 20.0
h = 1.0

In [73]:
y_list = []
inv_list = []

for r in r_list:
    
    # 異なる実質利子率の値で解を計算する
    a = np.array([[1-c, -1],[0,1]])
    b = np.array([g-d,f-h*r])
    sol = solve(a,b)
    
    y_list.append(sol[0].round(1))   # round(x)は小数点第x位まで四捨五入するメソッド
    inv_list.append(sol[1])

print('所得：', y_list)
print('投資：', inv_list)

所得： [66.7, 63.3, 60.0, 56.7, 53.3, 50.0, 46.7, 43.3, 40.0, 36.7]
投資： [20.0, 19.0, 18.0, 17.0, 16.0, 15.0, 14.0, 13.0, 12.0, 11.0]


In [74]:
n = len(r_list)        # r_listの要素数

y_arr = np.zeros(n)    # n個のゼロarray
inv_arr = np.zeros(n)  # n個のゼロarray

for i in range(n):

    a = np.array([[1-c, -1],[0,1]])
    b = np.array([g-d,f-h*r_list[i]])   # i番目のr_listを使う
    sol = solve(a,b)
    
    y_arr[i] = sol[0].round(1)   # i番目のy_arrに割り当てる
    inv_arr[i] = sol[1]          # i番目のinv_arrに割り当てる


print('所得：', y_arr)
print('投資：', inv_arr)

所得： [66.7 63.3 60.  56.7 53.3 50.  46.7 43.3 40.  36.7]
投資： [20. 19. 18. 17. 16. 15. 14. 13. 12. 11.]


In [75]:
y_list = []

for r in r_list:
    
    y = (f-h*r+g-d)/(1-c)
    y = round(y,1)         # round(x)は浮動小数点を四捨五入する関数
    y_list.append(y)

print('所得：', y_list)

所得： [66.7, 63.3, 60.0, 56.7, 53.3, 50.0, 46.7, 43.3, 40.0, 36.7]


In [76]:
n = len(r_list)        # r_listの要素数

y_arr = np.zeros(n)    # n個のゼロarray

for i in range(n):
    y_arr[i] = (f-h*r_list[i]+g-d)/(1-c)

print('所得：', y_arr.round(1))   # round()は四捨五入するメソッド

所得： [66.7 63.3 60.  56.7 53.3 50.  46.7 43.3 40.  36.7]


In [77]:
def y_equil(r):
    y = (f-h*r+g-d)/(1-c)
    return y.round(1)      # round()は四捨五入のメソッド

In [78]:
r_arr = np.array(r_list)
r_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
print('所得：', y_equil(r_arr))

所得： [66.7 63.3 60.  56.7 53.3 50.  46.7 43.3 40.  36.7]
